apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-virt

#resources:
#  - namespace.yaml

components:
  - ../components/vms/rhel9
  # be sure to update VM patches down below to match vlan and namespace
  - ../components/networks/vlan-1924

# the inline json patch can not learn of the random suffix
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: cloudinitdisk-rhel-node
    files:
      - scripts/userData

  - name: admin-kubeconfig
    files:
      - secrets/kubeconfig

patches:
- target:
    group: kubevirt.io
    kind: VirtualMachine
    name: rhel-node-1
    version: v1
  patch: |-
    - op: replace
      path: /spec/template/spec/domain/cpu/sockets
      value: 1

    - op: replace
      path: /spec/template/spec/volumes/1/cloudInitNoCloud
      value: {"secretRef":{"name":"cloudinitdisk-rhel-node"}}

    - op: add
      path: /spec/template/spec/volumes/-
      value: {"name":"admin-kubeconfig","secret":{"secretName":"admin-kubeconfig"}}

    - op: add
      path: /spec/template/spec/domain/devices/disks/-
      value: {"name":"admin-kubeconfig","serial": "admin-kubeconfig","disk":{"bus":"virtio"}}

    # note namespace in net-attach-def multus reference
    - op: replace
      path: /spec/template/spec/networks/0
      value: {"name":"nic-vlan-1924","multus":{"networkName":"demo-virt/vlan-1924"}}

    - op: replace
      path: /spec/template/spec/domain/devices/interfaces/0
      value: {"name": "nic-vlan-1924","bridge":{},"model":"virtio"}

    - op: replace
      path: /spec/running
      value: true
